vim.keymap.set('n', '<Tab>', ':BufferLineCycleNext<CR>')
vim.keymap.set('n', '<S-Tab>', ':BufferLineCyclePrev<CR>')
vim.keymap.set('n', '<leader>blr', ':BufferLineCloseRight<CR>')
vim.keymap.set('n', '<leader>bll', ':BufferLineCloseLeft<CR>')
vim.keymap.set('n', '<leader>blo', ':BufferLineCloseOthers<CR>')
vim.keymap.set('n', '<leader>bc', ':bd<CR>')
